import numpy as np
import pandas as pd
from scipy import ndimage

def cor_elev_pb(
    elev_grid: np.ndarray, diff_max: float, nb_max: int = 0, max_iter: int = 10, mask_size: tuple[int, int] = (3,3), ignore_center: bool=True) -> tuple[np.ndarray, np.ndarray, int]:
    """
    Corrige itérativement les pixels aberrants dans une grille d'élévation.
    Un pixel est considéré comme aberrant si sa valeur est inférieure à (moyenne des voisins - diff_max).
    La correction est répétée jusqu'à ce qu'il reste au plus `nb_max` pixels aberrants, ou que `max_iter` itérations soient atteintes.

    Args:

        elev_grid (np.ndarray): Grille 2D d'élévations.
        diff_max (float): Seuil maximal autorisé entre un pixel et la moyenne de ses voisins.
        nb_max (int): Nombre maximal de pixels aberrants acceptés pour arrêter la boucle. Par défaut, 0.
        max_iter (int): Nombre maximal d'itérations. Par défaut, 10.
        mask_size (tuple[int, int]): Taille du mask pour le calcul de la moyenne. Par défaut (3,3)
        ignore_center (bool): Ignorer le pixel central pour le calul de la moyenne du mask
        

    Returns:

        tuple[np.ndarray, np.ndarray, int]:
            - elev_pb: Masque booléen final des pixels aberrants (True = aberrant).
            - elev_cor: Grille corrigée.
            - iter: Nombre d'itérations effectuées.
    """
    # Masque pour les 8 voisins (exclut le centre)
    mask = np.ones(mask_size, dtype=bool)
    if ignore_center:
        mask[1,1] = False 

    # Initialisation
    elev_cor = elev_grid.copy()  # Évite de modifier l'entrée
    iter_count = 0
    nb_aberrants = elev_grid.size  # Initialise à une valeur > nb_max
    # Boucle de correction
    while nb_aberrants > nb_max and iter_count < max_iter:
        iter_count += 1
        # test_init = elev_cor[103][63]
        mean_elev = ndimage.generic_filter(elev_cor, np.nanmean, footprint=mask, mode='constant', cval=np.nan)
        test=elev_cor[103][63]
        # test_mean = mean_elev[103][63]
        # Identification des pixels aberrants
        elev_pb = elev_cor <= (mean_elev - diff_max)
        # test_pb = elev_pb[103][63]
        nb_aberrants = elev_pb.sum()
        # Correction : remplace les pixels aberrants par la moyenne de leurs voisins
        elev_cor = np.where(elev_pb, mean_elev, elev_cor)
        test_cor = elev_cor[103][63]
        # print(f"init : {test_init}, mean : {test_mean}, pb : {test_pb}, cor: {test_cor} ")
        # fig = ploting.create_plotly_map(elev_pb.astype(int), meta ,"Différence >0.4m", grids_hover=[elev_init], info_hover=["elev"], color="blues")
        # fig = ploting.create_plotly_map(elev_cor, meta ,"Différence >0.4m", grids_hover=[elev_init], info_hover=["elev"], color="rainbow")
        # fig.show()
        print("Iter ", iter_count, "  ", nb_aberrants, " pixels aberrants")

    return elev_pb, elev_cor, iter_count

def mod_elev_grid(elev_init: np.array, grid_luse: np.array, luse_dict: dict, mod_to_do: dict) -> np.array:
    """Modification of the elevation grid based on the land use grid

    Args:
        elev_init (np.array): Elevation grid (MNT)
        grid_luse (np.array): Land use grid
        luse_dict (dict): Landuse dictionnary, generated by read_file.create_dict_luse()
        mod_to_do (dict): Dictionnary of the elevation modification (in meter) to apply ex: {"bat": 5, "road": -0.1} to add 5m to bat pixels and subtract 0.1m to road pixels

    Returns:
        np.array: Modified elevation grid
    """
    elev_mod = elev_init.copy()
    for luse, mod in mod_to_do.items():
        print("Modifying elevation for ", luse, " with modification: ", mod)
        code_sol = [luse_dict[i]["id"] for i in luse_dict.keys() if luse_dict[i]["name"] == luse ][0]
        mask_to_mod = grid_luse == code_sol
        elev_mod = elev_mod + mod * mask_to_mod
    return elev_mod

def add_gully_luse(grid_gully: np.array, grid_luse: np.array, code_gully: int,) -> np.array:
    """Add the gullies to the landuse grid

    Args:
        grid_gully (np.array): grid with the gullies (pixel=1 when gully)
        grid_luse (np.array): Land use grid
        code_gully (int): Luse code use for the gullies

    Returns:
        np.array: _description_
    """
    data_luse_gully = grid_luse.copy()
    data_luse_gully[(grid_gully==1) & (~np.isnan(data_luse_gully))] = code_gully

    return data_luse_gully

def get_pos_gully(nodes_coord: pd.DataFrame, list_gully_nodes: list, metadata: dict):
    nrows = metadata["nrows"]
    cellsize = metadata["cellsize"]
    xllcorner = metadata["xllcorner"]
    yllcorner = metadata["yllcorner"]
    gully_pos = nodes_coord.copy()
    gully_pos = gully_pos.loc[gully_pos["Node"].isin(list_gully_nodes), ]
    # Find the position of eacg gully in the grid
    gully_pos["col"] = ((gully_pos.X - xllcorner) / cellsize).astype(int)
    gully_pos["row"] = nrows - 1 - np.floor((gully_pos.Y - yllcorner) / cellsize).astype(int)
    # Sorting the way MH find gullies in the landuse grid (top -> bottom, left -> right)
    gully_pos.sort_values(["row", "col"], inplace=True, ignore_index=True )

    return gully_pos

def correct_inflows_file(path_new_file: str, path_drainage_file:str ,gully_pos: pd.DataFrame) -> None :
    """Create a new drainage input file with sorted inflows lines to match the grids reading of MH

    Args:
        path_new_file (str): PAth to the new input drainage file
        gully_pos (pd.DataFrame): Dataframe of the gullies, must contain the columns Node, row, col

    Returns:
        None: Nothing
    """
    # Sorting the gully position
    gully_pos.sort_values(["row", "col"], inplace=True, ignore_index=True)
    with open(path_drainage_file, "r") as f:
        data= f.readlines()
    # Finding the index of infloxs line
    index_add_start = data.index("[INFLOWS]\n") + 4
    index_add_end = data.index("[TIMESERIES]\n") -1
    text_to_add = [f"{node}    FLOW    {i}    FLOW    1.0    1    \n" for node, i in 
                zip(gully_pos.Node, range(1,len(gully_pos.Node)+1))]
    # Replacing the inflows lines
    data[index_add_start:index_add_end] = text_to_add
    # Wrinting the new file
    with open(path_new_file, "w") as f:
        f.write("".join(data))
        print(f"{path_new_file} created with correct inflows")

    return None
    
